# Generated by Django 5.0.6 on 2024-05-13 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(max_length=100)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('browser_family', models.CharField(max_length=100)),
                ('browser_version', models.CharField(max_length=100)),
                ('os_family', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('device_family', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
